name: place_picker_meet
description: A Flutter plugin which provides 'Picking Place' using Google Maps widget.
version: 1.0.0
homepage: https://github.com/patelmeet341993/place_picker_meet

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  google_maps_flutter: ^2.10.0
#  google_maps_flutter_web: ^0.5.4+2
  geolocator: ^13.0.2
  provider: ^6.1.2
#  google_maps_webservice: ^0.0.20-nullsafety.5
  flutter_google_maps_webservices: ^1.1.1
  google_api_headers: '<=4.3.1'
  tuple:
  http:

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
